version: '3.8'

services:
  minerva_daq_logs:
    container_name: minerva_daq_logs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /work/logs/:/work/logs/
      - /work/data/rawdata:/work/data/rawdata
      - /work/data/dst:/work/data/dst
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/nearline_plots/event.png:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/nearline_plots/event.png