version: '3.8'

services:
  minerva_dqm_plots:
    container_name: minerva_dqm_plots
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/grafana/Mx2/:/data/grafana/Mx2/
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/nearline_plots:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/nearline_plots
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/last_log_entry.txt
      - /home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/Roboto-Medium.ttf:/home/acd/acdcs/2x2/MINERvA_DQM_PlotTransfer/Roboto-Medium.ttf